import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

// prisma/seed.ts
export async function seed1() {
  await db.mixData.create({
    data: {
      name: "ubu",
      data: JSON.stringify({
        formatName: "dexie",
        formatVersion: 1,
        data: {
          databaseName: "mixerDb",
          databaseVersion: 1,
          tables: [
            { name: "sourceSong", schema: "++id", rowCount: 1 },
            { name: "currentMain", schema: "++id", rowCount: 1 },
            {
              name: "currentTracks",
              schema:
                "++id,name,path,volume,volumeMode,panMode,soloMuteMode,pan,soloMute,fxNames,delaySettings,reverbSettings,pitchShiftSettings,panelPosition,panelActive,panelSize",
              rowCount: 4,
            },
            { name: "volumeData", schema: "++id", rowCount: 0 },
            { name: "panData", schema: "++id", rowCount: 0 },
            { name: "soloMuteData", schema: "++id", rowCount: 0 },
            { name: "delayData", schema: "++id", rowCount: 0 },
            { name: "reverbData", schema: "++id", rowCount: 0 },
            { name: "pitchShiftData", schema: "++id", rowCount: 0 },
          ],
          data: [
            {
              tableName: "sourceSong",
              inbound: true,
              rows: [
                {
                  id: "sourceSong",
                  data: {
                    id: "l34kj53lk5j35l3jk",
                    title: "Roxanne",
                    artist: "The Police",
                    year: "1978",
                    studio: "Surrey Sound Studios",
                    location: "Leatherhead, Surrey, U.K.",
                    slug: "roxanne",
                    bpm: 92,
                    start: 1,
                    end: 180,
                    tracks: [
                      {
                        id: "a784ef3a-8d46-48bf-a70f-8c38e9c7011e",
                        name: "Drums",
                        path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Drums.mp3",
                      },
                      {
                        id: "8fecbdbc-23e8-4612-889e-8babb3a2be71",
                        name: "Bass",
                        path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Bass.mp3",
                      },
                      {
                        id: "10fcb580-702f-4290-bec0-ff51f48fe52b",
                        name: "Guitar",
                        path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Guitar.mp3",
                      },
                      {
                        id: "3b7dcecc-ac85-4260-bf57-0c888d8218e3",
                        name: "Vocals",
                        path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Vocal.mp3",
                      },
                    ],
                  },
                  $types: { "data.tracks": "arrayNonindexKeys" },
                },
              ],
            },
            {
              tableName: "currentMain",
              inbound: true,
              rows: [{ id: "currentMain", data: { volume: -32 } }],
            },
            {
              tableName: "currentTracks",
              inbound: true,
              rows: [
                {
                  name: "Drums",
                  path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Drums.mp3",
                  volume: -32,
                  volumeMode: "static",
                  panMode: "static",
                  soloMuteMode: "static",
                  pan: 0,
                  soloMute: { solo: false, mute: false },
                  fxNames: [],
                  delaySettings: {
                    playbackMode: "static",
                    delayBypass: [false, false],
                    delayMix: [0.5, 0.5],
                    delayTime: [1, 1],
                    delayFeedback: [0.5, 0.5],
                  },
                  reverbSettings: {
                    playbackMode: "static",
                    reverbBypass: [false, false],
                    reverbMix: [0.5, 0.5],
                    reverbPreDelay: [0.5, 0.5],
                    reverbDecay: [0.5, 0.5],
                  },
                  pitchShiftSettings: {
                    playbackMode: "static",
                    pitchShiftBypass: [false, false],
                    pitchShiftMix: [0.5, 0.5],
                    pitchShiftPitch: [5, 5],
                  },
                  panelPosition: { x: 0, y: 0 },
                  panelActive: false,
                  panelSize: { width: "325px", height: "auto" },
                  id: 1,
                  $types: {
                    fxNames: "arrayNonindexKeys",
                    "delaySettings.delayBypass": "arrayNonindexKeys",
                    "delaySettings.delayMix": "arrayNonindexKeys",
                    "delaySettings.delayTime": "arrayNonindexKeys",
                    "delaySettings.delayFeedback": "arrayNonindexKeys",
                    "reverbSettings.reverbBypass": "arrayNonindexKeys",
                    "reverbSettings.reverbMix": "arrayNonindexKeys",
                    "reverbSettings.reverbPreDelay": "arrayNonindexKeys",
                    "reverbSettings.reverbDecay": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftBypass": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftMix": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftPitch": "arrayNonindexKeys",
                  },
                },
                {
                  name: "Bass",
                  path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Bass.mp3",
                  volume: -32,
                  volumeMode: "static",
                  panMode: "static",
                  soloMuteMode: "static",
                  pan: 0,
                  soloMute: { solo: false, mute: false },
                  fxNames: [],
                  delaySettings: {
                    playbackMode: "static",
                    delayBypass: [false, false],
                    delayMix: [0.5, 0.5],
                    delayTime: [1, 1],
                    delayFeedback: [0.5, 0.5],
                  },
                  reverbSettings: {
                    playbackMode: "static",
                    reverbBypass: [false, false],
                    reverbMix: [0.5, 0.5],
                    reverbPreDelay: [0.5, 0.5],
                    reverbDecay: [0.5, 0.5],
                  },
                  pitchShiftSettings: {
                    playbackMode: "static",
                    pitchShiftBypass: [false, false],
                    pitchShiftMix: [0.5, 0.5],
                    pitchShiftPitch: [5, 5],
                  },
                  panelPosition: { x: 0, y: 0 },
                  panelActive: false,
                  panelSize: { width: "325px", height: "auto" },
                  id: 2,
                  $types: {
                    fxNames: "arrayNonindexKeys",
                    "delaySettings.delayBypass": "arrayNonindexKeys",
                    "delaySettings.delayMix": "arrayNonindexKeys",
                    "delaySettings.delayTime": "arrayNonindexKeys",
                    "delaySettings.delayFeedback": "arrayNonindexKeys",
                    "reverbSettings.reverbBypass": "arrayNonindexKeys",
                    "reverbSettings.reverbMix": "arrayNonindexKeys",
                    "reverbSettings.reverbPreDelay": "arrayNonindexKeys",
                    "reverbSettings.reverbDecay": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftBypass": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftMix": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftPitch": "arrayNonindexKeys",
                  },
                },
                {
                  name: "Guitar",
                  path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Guitar.mp3",
                  volume: -32,
                  volumeMode: "static",
                  panMode: "static",
                  soloMuteMode: "static",
                  pan: 0,
                  soloMute: { solo: false, mute: false },
                  fxNames: [],
                  delaySettings: {
                    playbackMode: "static",
                    delayBypass: [false, false],
                    delayMix: [0.5, 0.5],
                    delayTime: [1, 1],
                    delayFeedback: [0.5, 0.5],
                  },
                  reverbSettings: {
                    playbackMode: "static",
                    reverbBypass: [false, false],
                    reverbMix: [0.5, 0.5],
                    reverbPreDelay: [0.5, 0.5],
                    reverbDecay: [0.5, 0.5],
                  },
                  pitchShiftSettings: {
                    playbackMode: "static",
                    pitchShiftBypass: [false, false],
                    pitchShiftMix: [0.5, 0.5],
                    pitchShiftPitch: [5, 5],
                  },
                  panelPosition: { x: 0, y: 0 },
                  panelActive: false,
                  panelSize: { width: "325px", height: "auto" },
                  id: 3,
                  $types: {
                    fxNames: "arrayNonindexKeys",
                    "delaySettings.delayBypass": "arrayNonindexKeys",
                    "delaySettings.delayMix": "arrayNonindexKeys",
                    "delaySettings.delayTime": "arrayNonindexKeys",
                    "delaySettings.delayFeedback": "arrayNonindexKeys",
                    "reverbSettings.reverbBypass": "arrayNonindexKeys",
                    "reverbSettings.reverbMix": "arrayNonindexKeys",
                    "reverbSettings.reverbPreDelay": "arrayNonindexKeys",
                    "reverbSettings.reverbDecay": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftBypass": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftMix": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftPitch": "arrayNonindexKeys",
                  },
                },
                {
                  name: "Vocals",
                  path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Vocal.mp3",
                  volume: -32,
                  volumeMode: "static",
                  panMode: "static",
                  soloMuteMode: "static",
                  pan: 0,
                  soloMute: { solo: false, mute: false },
                  fxNames: [],
                  delaySettings: {
                    playbackMode: "static",
                    delayBypass: [false, false],
                    delayMix: [0.5, 0.5],
                    delayTime: [1, 1],
                    delayFeedback: [0.5, 0.5],
                  },
                  reverbSettings: {
                    playbackMode: "static",
                    reverbBypass: [false, false],
                    reverbMix: [0.5, 0.5],
                    reverbPreDelay: [0.5, 0.5],
                    reverbDecay: [0.5, 0.5],
                  },
                  pitchShiftSettings: {
                    playbackMode: "static",
                    pitchShiftBypass: [false, false],
                    pitchShiftMix: [0.5, 0.5],
                    pitchShiftPitch: [5, 5],
                  },
                  panelPosition: { x: 0, y: 0 },
                  panelActive: false,
                  panelSize: { width: "325px", height: "auto" },
                  id: 4,
                  $types: {
                    fxNames: "arrayNonindexKeys",
                    "delaySettings.delayBypass": "arrayNonindexKeys",
                    "delaySettings.delayMix": "arrayNonindexKeys",
                    "delaySettings.delayTime": "arrayNonindexKeys",
                    "delaySettings.delayFeedback": "arrayNonindexKeys",
                    "reverbSettings.reverbBypass": "arrayNonindexKeys",
                    "reverbSettings.reverbMix": "arrayNonindexKeys",
                    "reverbSettings.reverbPreDelay": "arrayNonindexKeys",
                    "reverbSettings.reverbDecay": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftBypass": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftMix": "arrayNonindexKeys",
                    "pitchShiftSettings.pitchShiftPitch": "arrayNonindexKeys",
                  },
                },
              ],
            },
            { tableName: "volumeData", inbound: true, rows: [] },
            { tableName: "panData", inbound: true, rows: [] },
            { tableName: "soloMuteData", inbound: true, rows: [] },
            { tableName: "delayData", inbound: true, rows: [] },
            { tableName: "reverbData", inbound: true, rows: [] },
            { tableName: "pitchShiftData", inbound: true, rows: [] },
          ],
        },
      }),
    },
  });
}
